"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from distutils.core import setup

from Cython.Build import cythonize

APP = ['main.py']
DATA_FILES = [
    ('ui', './ui/main.qml'),
    ('ui', './ui/Operation.qml'),
    ('ui', './ui/medleap.qml'),
    ('ui', './ui/MaterialIcons.js'),
    ('ui', './ui/LabdevSettings.qml'),
    ('ui', './ui/DbSetting.qml'),
    ('ui/resources', './ui/resources/materialdesignicons-webfont.ttf'),
    ('ui/image', './ui/image/medleap.png')
]
OPTIONS = {}

setup(
    name='medleap',
    data_files=DATA_FILES,
    ext_modules=cythonize(['./**/*.py'], build_dir='build/')
)
